/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SessionMgmtFilters {
	def sessionService
	
    def filters = {
		timeout(uri: "/heartbeat/**") {
			before = {
				// NOP
			}
		}

		startApp(uri: "/app/**") {
			before = {
		        sessionService.registerSessionActivity()			
			}
		}
    }
}
